### PR TITLE
Updated index.html and added icons

### PR DESCRIPTION
**Pull request by shuklaritvik06**
What I have done?

Added some icons , added hyper link to the mail
 
### Previous
Screenshot from 2021-08-20 12-45-06

### Now
Screenshot from 2021-08-20 12-43-51
Screenshot from 2021-08-20 12-43-59
Screenshot from 2021-08-20 12-44-10

### CODE REVIEW

**Comment by shuklaritvik06** [comment]
Should I add an auto-subscribe link to the youtube channel @kunal-kushwaha ?

**Comment by samjn08** [comment]
There are four more files that you can change:
1) [javadsabootcamp.html](courses/javadsabootcamp.html)
2) [gitandgithub.html](courses/gitandgithub.html)
3) [javadsabootcampmain.html](courses/coursesmain/javadsabootcampmain.html)
4) [gitandgithubmain.html](courses/coursesmain/gitandgithubmain.html)

**Comment by samjn08** [comment]
There are four more files that you can change:
1) [javadsabootcamp.html](https://github.com/kunal-kushwaha/commclassroom/blob/master/courses/javadsabootcamp.html)
2) [gitandgithub.html](https://github.com/kunal-kushwaha/commclassroom/blob/master/courses/gitandgithub.html)
3) [javadsabootcampmain.html](https://github.com/kunal-kushwaha/commclassroom/blob/master/courses/coursesmain/javadsabootcampmain.html)
4) [gitandgithubmain.html](https://github.com/kunal-kushwaha/commclassroom/blob/master/courses/coursesmain/gitandgithubmain.html)

**Comment by shuklaritvik06** [comment]
> There are four more files that you can change:
> 
>     1. [javadsabootcamp.html](https://github.com/kunal-kushwaha/commclassroom/blob/master/courses/javadsabootcamp.html)
> 
>     2. [gitandgithub.html](https://github.com/kunal-kushwaha/commclassroom/blob/master/courses/gitandgithub.html)
> 
>     3. [javadsabootcampmain.html](https://github.com/kunal-kushwaha/commclassroom/blob/master/courses/coursesmain/javadsabootcampmain.html)
> 
>     4. [gitandgithubmain.html](https://github.com/kunal-kushwaha/commclassroom/blob/master/courses/coursesmain/gitandgithubmain.html)

Yeah , sorry I haven't seen that , i will make the changes

**Comment by shuklaritvik06** [comment]
@samjn08  please review now!

**Comment by samjn08** [comment]
@shuklaritvik06 yes, please add ?sub_confirmation=1 after the link!

**Comment by shuklaritvik06** [comment]
> @shuklaritvik06 yes, please add ?sub_confirmation=1 after the link!

Yeahhh !

**Comment by samjn08** [comment]
@shuklaritvik06 but I tried it on pc, it's working. Are you trying on mobile??

**Comment by shuklaritvik06** [comment]
> @shuklaritvik06 but I tried it on pc, it's working. Are you trying on mobile??

Nope on pc only os-ubuntu 21.04

**Comment by shuklaritvik06** [comment]
> @shuklaritvik06 but I tried it on pc, it's working. Are you trying on mobile??

Notification is on or off for the channel? The subscription part works correctly but the problem comes in notification bell part

**Comment by samjn08** [comment]
@shuklaritvik06 maybe you are trying with an id by which you have already subscribed the channel!

**Comment by shuklaritvik06** [comment]
> @shuklaritvik06 maybe you are trying with an id by which you have already subscribed the channel! log out and then try

see this i tried from a new id (my college one) 

Screenshot from 2021-08-20 19-16-07

**Comment by samjn08** [comment]
@shuklaritvik06 I can turn on the notifications on my device. Maybe it's a problem of your browser. I think you should go ahead, add the updated link!

**Comment by shuklaritvik06** [comment]
> @shuklaritvik06 I can turn on the notifications on my device. Maybe it's a problem of your browser. I think you should go ahead, add the updated link!

Yeah sure :)

**Pull request closed without merging**
